// WordMaster 单词数据
const wordDatabase = {
    cet4: [
        { word: "abandon", phonetic: "/əˈbændən/", meaning: "v. 放弃，抛弃", example: { en: "He abandoned his car and ran for help.", cn: "他弃车跑去求救。" } },
        { word: "ability", phonetic: "/əˈbɪləti/", meaning: "n. 能力，才能", example: { en: "She has the ability to solve complex problems.", cn: "她有能力解决复杂问题。" } },
        { word: "absence", phonetic: "/ˈæbsəns/", meaning: "n. 缺席，缺乏", example: { en: "His absence from class was noticed by the teacher.", cn: "老师注意到他缺课了。" } },
        { word: "absolute", phonetic: "/ˈæbsəluːt/", meaning: "adj. 绝对的，完全的", example: { en: "I have absolute confidence in your ability.", cn: "我对你有绝对的信心。" } },
        { word: "absorb", phonetic: "/əbˈzɔːrb/", meaning: "v. 吸收，吸引", example: { en: "The sponge can absorb a lot of water.", cn: "海绵能吸收大量水分。" } },
        { word: "abstract", phonetic: "/ˈæbstrækt/", meaning: "adj. 抽象的；n. 摘要", example: { en: "The painting is very abstract and hard to understand.", cn: "这幅画很抽象，难以理解。" } },
        { word: "abundant", phonetic: "/əˈbʌndənt/", meaning: "adj. 丰富的，充裕的", example: { en: "The region has abundant natural resources.", cn: "该地区有丰富的自然资源。" } },
        { word: "academic", phonetic: "/ˌækəˈdemɪk/", meaning: "adj. 学术的，学院的", example: { en: "She has excellent academic performance.", cn: "她的学业成绩优异。" } },
        { word: "academy", phonetic: "/əˈkædəmi/", meaning: "n. 学院，研究院", example: { en: "He graduated from a military academy.", cn: "他毕业于军事学院。" } },
        { word: "accelerate", phonetic: "/əkˈseləreɪt/", meaning: "v. 加速，促进", example: { en: "The car accelerated rapidly on the highway.", cn: "汽车在高速公路上迅速加速。" } },
        { word: "accent", phonetic: "/ˈæksent/", meaning: "n. 口音，重音", example: { en: "She speaks English with a French accent.", cn: "她讲英语带有法国口音。" } },
        { word: "accept", phonetic: "/əkˈsept/", meaning: "v. 接受，认可", example: { en: "I accept your apology.", cn: "我接受你的道歉。" } },
        { word: "access", phonetic: "/ˈækses/", meaning: "n. 通道，入口；v. 存取", example: { en: "Students have access to the library resources.", cn: "学生可以使用图书馆资源。" } },
        { word: "accident", phonetic: "/ˈæksɪdənt/", meaning: "n. 事故，意外", example: { en: "There was a car accident on the highway.", cn: "高速公路上发生了车祸。" } },
        { word: "accompany", phonetic: "/əˈkʌmpəni/", meaning: "v. 陪伴，伴随", example: { en: "She accompanied me to the hospital.", cn: "她陪我去医院。" } },
        { word: "accomplish", phonetic: "/əˈkʌmplɪʃ/", meaning: "v. 完成，实现", example: { en: "We accomplished our mission successfully.", cn: "我们成功完成了任务。" } },
        { word: "accord", phonetic: "/əˈkɔːrd/", meaning: "v. 一致，符合；n. 协议", example: { en: "His views are in accord with mine.", cn: "他的观点与我一致。" } },
        { word: "account", phonetic: "/əˈkaʊnt/", meaning: "n. 账户，解释；v. 说明", example: { en: "I need to open a bank account.", cn: "我需要开一个银行账户。" } },
        { word: "accumulate", phonetic: "/əˈkjuːmjəleɪt/", meaning: "v. 积累，堆积", example: { en: "Dust began to accumulate on the shelves.", cn: "灰尘开始在架子上堆积。" } },
        { word: "accurate", phonetic: "/ˈækjərət/", meaning: "adj. 精确的，准确的", example: { en: "The weather forecast is quite accurate.", cn: "天气预报相当准确。" } },
        { word: "accuse", phonetic: "/əˈkjuːz/", meaning: "v. 控告，指责", example: { en: "He was accused of stealing money.", cn: "他被指控偷钱。" } },
        { word: "achieve", phonetic: "/əˈtʃiːv/", meaning: "v. 达到，实现", example: { en: "She worked hard to achieve her goals.", cn: "她努力实现自己的目标。" } },
        { word: "achievement", phonetic: "/əˈtʃiːvmənt/", meaning: "n. 成就，成绩", example: { en: "Winning the championship was a great achievement.", cn: "赢得冠军是一项伟大的成就。" } },
        { word: "acid", phonetic: "/ˈæsɪd/", meaning: "n. 酸，酸性物质", example: { en: "Vinegar contains acetic acid.", cn: "醋含有醋酸。" } },
        { word: "acknowledge", phonetic: "/əkˈnɑːlɪdʒ/", meaning: "v. 承认，致谢", example: { en: "I acknowledge that I made a mistake.", cn: "我承认我犯了错误。" } },
        { word: "acquire", phonetic: "/əˈkwaɪər/", meaning: "v. 获得，学到", example: { en: "She acquired a new skill during the training.", cn: "她在培训期间学到了新技能。" } },
        { word: "acquisition", phonetic: "/ˌækwɪˈzɪʃn/", meaning: "n. 获得，收购", example: { en: "The company announced the acquisition of a startup.", cn: "公司宣布收购一家初创企业。" } },
        { word: "acre", phonetic: "/ˈeɪkər/", meaning: "n. 英亩", example: { en: "The farm covers over 100 acres.", cn: "这个农场占地超过100英亩。" } },
        { word: "across", phonetic: "/əˈkrɔːs/", meaning: "prep. 穿过，横过", example: { en: "We walked across the bridge.", cn: "我们走过桥。" } },
        { word: "act", phonetic: "/ækt/", meaning: "v. 行动，表演；n. 行为", example: { en: "We must act quickly to solve this problem.", cn: "我们必须迅速行动来解决这个问题。" } }
    ],
    cet6: [
        { word: "abbreviate", phonetic: "/əˈbriːvieɪt/", meaning: "v. 缩写，缩短", example: { en: "Please abbreviate your answer to one page.", cn: "请将你的答案缩短到一页。" } },
        { word: "abnormal", phonetic: "/æbˈnɔːrml/", meaning: "adj. 反常的，异常的", example: { en: "The test showed an abnormal result.", cn: "测试显示了异常结果。" } },
        { word: "abolish", phonetic: "/əˈbɑːlɪʃ/", meaning: "v. 废除，废止", example: { en: "Slavery was abolished in the 19th century.", cn: "奴隶制在19世纪被废除。" } },
        { word: "abrupt", phonetic: "/əˈbrʌpt/", meaning: "adj. 突然的，唐突的", example: { en: "The car came to an abrupt stop.", cn: "汽车突然停了下来。" } },
        { word: "absurd", phonetic: "/əbˈsɜːrd/", meaning: "adj. 荒谬的，可笑的", example: { en: "That's an absurd idea.", cn: "那是个荒谬的想法。" } },
        { word: "abundance", phonetic: "/əˈbʌndəns/", meaning: "n. 丰富，充裕", example: { en: "The region has an abundance of wildlife.", cn: "该地区有丰富的野生动物。" } },
        { word: "accessory", phonetic: "/əkˈsesəri/", meaning: "n. 附件，配饰", example: { en: "She bought some accessories for her phone.", cn: "她为手机买了一些配件。" } },
        { word: "accommodate", phonetic: "/əˈkɑːmədeɪt/", meaning: "v. 容纳，适应", example: { en: "The hotel can accommodate 500 guests.", cn: "这家酒店可以容纳500位客人。" } },
        { word: "accommodation", phonetic: "/əˌkɑːməˈdeɪʃn/", meaning: "n. 住处，膳宿", example: { en: "We need to find accommodation for the night.", cn: "我们需要找地方过夜。" } },
        { word: "accordance", phonetic: "/əˈkɔːrdns/", meaning: "n. 一致，按照", example: { en: "In accordance with the rules, he was fined.", cn: "根据规定，他被罚款了。" } },
        { word: "accordingly", phonetic: "/əˈkɔːrdɪŋli/", meaning: "adv. 因此，相应地", example: { en: "He was told to speak briefly; accordingly, he cut short his remarks.", cn: "他被告知要简短发言，因此他缩短了讲话。" } },
        { word: "accountant", phonetic: "/əˈkaʊntənt/", meaning: "n. 会计师", example: { en: "You should consult an accountant about your taxes.", cn: "你应该就税务问题咨询会计师。" } },
        { word: "accumulation", phonetic: "/əˌkjuːmjəˈleɪʃn/", meaning: "n. 积累，堆积物", example: { en: "The accumulation of data takes time.", cn: "数据的积累需要时间。" } },
        { word: "accuracy", phonetic: "/ˈækjərəsi/", meaning: "n. 准确性，精确度", example: { en: "The accuracy of the report was questioned.", cn: "报告的准确性受到质疑。" } },
        { word: "accustomed", phonetic: "/əˈkʌstəmd/", meaning: "adj. 习惯的，通常的", example: { en: "I am accustomed to getting up early.", cn: "我习惯早起。" } },
        { word: "acidic", phonetic: "/əˈsɪdɪk/", meaning: "adj. 酸的，酸性的", example: { en: "The soil in this region is too acidic for most crops.", cn: "这个地区的土壤对大多数作物来说太酸了。" } },
        { word: "activate", phonetic: "/ˈæktɪveɪt/", meaning: "v. 激活，使活动", example: { en: "You need to activate your account first.", cn: "你需要先激活你的账户。" } },
        { word: "addict", phonetic: "/ˈædɪkt/", meaning: "n. 上瘾者；v. 使上瘾", example: { en: "He is a recovering drug addict.", cn: "他是一个正在康复的吸毒者。" } },
        { word: "addiction", phonetic: "/əˈdɪkʃn/", meaning: "n. 上瘾，沉溺", example: { en: "He is fighting an addiction to gambling.", cn: "他正在与赌瘾作斗争。" } },
        { word: "adequate", phonetic: "/ˈædɪkwət/", meaning: "adj. 足够的，适当的", example: { en: "The food was adequate but not special.", cn: "食物足够但没什么特别的。" } },
        { word: "adhere", phonetic: "/ədˈhɪr/", meaning: "v. 粘附，坚持", example: { en: "We must adhere to the rules.", cn: "我们必须遵守规则。" } },
        { word: "adjacent", phonetic: "/əˈdʒeɪsnt/", meaning: "adj. 邻近的，毗邻的", example: { en: "The building adjacent to the school is a library.", cn: "学校旁边的建筑是图书馆。" } },
        { word: "adjoin", phonetic: "/əˈdʒɔɪn/", meaning: "v. 毗连，靠近", example: { en: "The bathroom adjoins the bedroom.", cn: "浴室与卧室相连。" } },
        { word: "administer", phonetic: "/ədˈmɪnɪstər/", meaning: "v. 管理，执行", example: { en: "The test was administered to all students.", cn: "所有学生都参加了测试。" } },
        { word: "adolescent", phonetic: "/ˌædəˈlesnt/", meaning: "n. 青少年；adj. 青春期的", example: { en: "Adolescents often have mood swings.", cn: "青少年经常有情绪波动。" } },
        { word: "adoption", phonetic: "/əˈdɑːpʃn/", meaning: "n. 采用，收养", example: { en: "The adoption of new technology takes time.", cn: "新技术的采用需要时间。" } },
        { word: "adore", phonetic: "/əˈdɔːr/", meaning: "v. 崇拜，爱慕", example: { en: "She adores her grandchildren.", cn: "她非常疼爱她的孙子孙女。" } },
        { word: "advantageous", phonetic: "/ˌædvənˈteɪdʒəs/", meaning: "adj. 有利的，有益的", example: { en: "The new location is advantageous for business.", cn: "新地点对生意有利。" } },
        { word: "adverse", phonetic: "/ədˈvɜːrs/", meaning: "adj. 不利的，相反的", example: { en: "The project was delayed due to adverse weather.", cn: "由于恶劣天气，项目被推迟了。" } },
        { word: "advocate", phonetic: "/ˈædvəkeɪt/", meaning: "v. 提倡，主张；n. 提倡者", example: { en: "She advocates for environmental protection.", cn: "她提倡环境保护。" } }
    ],
    ielts: [
        { word: "aberration", phonetic: "/ˌæbəˈreɪʃn/", meaning: "n. 异常，脱离常规", example: { en: "The poor test result was an aberration.", cn: "这次糟糕的测试结果是个异常。" } },
        { word: "abet", phonetic: "/əˈbet/", meaning: "v. 教唆，怂恿", example: { en: "He was accused of aiding and abetting the crime.", cn: "他被指控协助和教唆犯罪。" } },
        { word: "abeyance", phonetic: "/əˈbeɪəns/", meaning: "n. 中止，暂缓", example: { en: "The project is in abeyance until funding is secured.", cn: "项目在获得资金之前暂停。" } },
        { word: "abhor", phonetic: "/əbˈhɔːr/", meaning: "v. 憎恶，厌恶", example: { en: "I abhor violence of any kind.", cn: "我憎恶任何形式的暴力。" } },
        { word: "abject", phonetic: "/ˈæbdʒekt/", meaning: "adj. 凄惨的，卑鄙的", example: { en: "They lived in abject poverty.", cn: "他们生活在赤贫中。" } },
        { word: "abjure", phonetic: "/əbˈdʒʊr/", meaning: "v. 发誓放弃，公开放弃", example: { en: "He abjured his religion.", cn: "他发誓放弃自己的宗教信仰。" } },
        { word: "ablution", phonetic: "/əˈbluːʃn/", meaning: "n. 沐浴，洗礼", example: { en: "He performed his morning ablutions.", cn: "他进行了晨间洗漱。" } },
        { word: "abnegation", phonetic: "/ˌæbnɪˈɡeɪʃn/", meaning: "n. 放弃，自我否定", example: { en: "Her abnegation of luxury impressed everyone.", cn: "她放弃奢华的生活方式给所有人留下了深刻印象。" } },
        { word: "abominate", phonetic: "/əˈbɑːmɪneɪt/", meaning: "v. 痛恨，憎恶", example: { en: "He abominates cruelty to animals.", cn: "他痛恨虐待动物。" } },
        { word: "aboriginal", phonetic: "/ˌæbəˈrɪdʒənl/", meaning: "adj. 土著的，原始的", example: { en: "The aboriginal people have lived here for thousands of years.", cn: "土著人民在这里生活了数千年。" } },
        { word: "abortive", phonetic: "/əˈbɔːrtɪv/", meaning: "adj. 失败的，流产的", example: { en: "The rescue attempt was abortive.", cn: "救援尝试失败了。" } },
        { word: "abrade", phonetic: "/əˈbreɪd/", meaning: "v. 磨损，擦伤", example: { en: "The rocks were abraded by wind and water.", cn: "岩石被风和水磨损。" } },
        { word: "abridge", phonetic: "/əˈbrɪdʒ/", meaning: "v. 删节，缩短", example: { en: "The novel was abridged for radio.", cn: "这部小说被删节用于广播。" } },
        { word: "abrogate", phonetic: "/ˈæbrəɡeɪt/", meaning: "v. 废除，取消", example: { en: "The treaty was abrogated by the new government.", cn: "新政府废除了该条约。" } },
        { word: "abscond", phonetic: "/əbˈskɑːnd/", meaning: "v. 潜逃，逃亡", example: { en: "The thief absconded with the money.", cn: "小偷携款潜逃。" } },
        { word: "absolve", phonetic: "/əbˈzɑːlv/", meaning: "v. 赦免，免除", example: { en: "The priest absolved him of his sins.", cn: "神父赦免了他的罪。" } },
        { word: "abstain", phonetic: "/əbˈsteɪn/", meaning: "v. 弃权，戒除", example: { en: "He decided to abstain from voting.", cn: "他决定弃权不投票。" } },
        { word: "abstemious", phonetic: "/əbˈstiːmiəs/", meaning: "adj. 节俭的，有节制的", example: { en: "He leads an abstemious life.", cn: "他过着节俭的生活。" } },
        { word: "abstinence", phonetic: "/ˈæbstɪnəns/", meaning: "n. 节制，禁欲", example: { en: "The doctor recommended total abstinence from alcohol.", cn: "医生建议完全戒酒。" } },
        { word: "abstracted", phonetic: "/æbˈstræktɪd/", meaning: "adj. 心不在焉的", example: { en: "She seemed abstracted during the meeting.", cn: "她在会议期间显得心不在焉。" } },
        { word: "abstruse", phonetic: "/əbˈstruːs/", meaning: "adj. 深奥的，难懂的", example: { en: "The professor's lecture was too abstruse for most students.", cn: "教授的讲座对大多数学生来说太深奥了。" } },
        { word: "abut", phonetic: "/əˈbʌt/", meaning: "v. 邻接，毗邻", example: { en: "The park abuts on the school grounds.", cn: "公园与学校场地相邻。" } },
        { word: "abysmal", phonetic: "/əˈbɪzməl/", meaning: "adj. 极坏的，深不可测的", example: { en: "The weather was abysmal all week.", cn: "整个星期的天气都很糟糕。" } },
        { word: "accede", phonetic: "/əkˈsiːd/", meaning: "v. 同意，加入", example: { en: "The government acceded to the demands.", cn: "政府同意了这些要求。" } },
        { word: "accelerator", phonetic: "/əkˈseləreɪtər/", meaning: "n. 加速器，油门", example: { en: "He pressed the accelerator to speed up.", cn: "他踩油门加速。" } },
        { word: "accentuate", phonetic: "/əkˈsentʃueɪt/", meaning: "v. 强调，重读", example: { en: "The lighting accentuated the colors in the painting.", cn: "灯光突出了画中的色彩。" } },
        { word: "accessible", phonetic: "/əkˈsesəbl/", meaning: "adj. 可到达的，易接近的", example: { en: "The museum is accessible to wheelchair users.", cn: "博物馆对轮椅使用者是可进入的。" } },
        { word: "accession", phonetic: "/əkˈseʃn/", meaning: "n. 就职，加入", example: { en: "The accession of the new king was celebrated.", cn: "新国王的即位受到庆祝。" } },
        { word: "acclaim", phonetic: "/əˈkleɪm/", meaning: "v. 称赞，欢呼", example: { en: "The film was acclaimed by critics.", cn: "这部电影受到评论家的称赞。" } },
        { word: "acclimate", phonetic: "/ˈækləmeɪt/", meaning: "v. 适应，服水土", example: { en: "It takes time to acclimate to a new environment.", cn: "适应新环境需要时间。" } }
    ],
    toefl: [
        { word: "abase", phonetic: "/əˈbeɪs/", meaning: "v. 贬低，使谦卑", example: { en: "He refused to abase himself before the tyrant.", cn: "他拒绝在暴君面前卑躬屈膝。" } },
        { word: "abate", phonetic: "/əˈbeɪt/", meaning: "v. 减少，减轻", example: { en: "The storm began to abate.", cn: "暴风雨开始减弱。" } },
        { word: "abdicate", phonetic: "/ˈæbdɪkeɪt/", meaning: "v. 退位，放弃", example: { en: "The king was forced to abdicate.", cn: "国王被迫退位。" } },
        { word: "aberrant", phonetic: "/æˈberənt/", meaning: "adj. 异常的，脱离常规的", example: { en: "This aberrant behavior needs to be addressed.", cn: "这种异常行为需要解决。" } },
        { word: "abet", phonetic: "/əˈbet/", meaning: "v. 教唆，帮助", example: { en: "He was found guilty of aiding and abetting.", cn: "他被判协助和教唆罪。" } },
        { word: "abeyant", phonetic: "/əˈbeɪənt/", meaning: "adj. 暂时中止的", example: { en: "The issue remains abeyant.", cn: "这个问题仍然悬而未决。" } },
        { word: "abhorrence", phonetic: "/əbˈhɔːrəns/", meaning: "n. 憎恶，厌恶", example: { en: "She has an abhorrence of violence.", cn: "她憎恶暴力。" } },
        { word: "abjectly", phonetic: "/ˈæbdʒektli/", meaning: "adv. 悲惨地，卑鄙地", example: { en: "He abjectly apologized for his mistake.", cn: "他为自己的错误卑躬屈膝地道歉。" } },
        { word: "abjuration", phonetic: "/ˌæbdʒʊˈreɪʃn/", meaning: "n. 发誓放弃", example: { en: "His abjuration of his former beliefs shocked everyone.", cn: "他发誓放弃以前的信仰震惊了所有人。" } },
        { word: "ablaze", phonetic: "/əˈbleɪz/", meaning: "adj. 燃烧的，闪耀的", example: { en: "The building was set ablaze.", cn: "大楼被点燃了。" } },
        { word: "able-bodied", phonetic: "/ˌeɪbl ˈbɑːdid/", meaning: "adj. 强壮的，健全的", example: { en: "All able-bodied men were required to serve.", cn: "所有身体健全的男性都被要求服役。" } },
        { word: "abnegate", phonetic: "/ˈæbnɪɡeɪt/", meaning: "v. 放弃，否认", example: { en: "He abnegated all claims to the throne.", cn: "他放弃了对王位的一切要求。" } },
        { word: "abominable", phonetic: "/əˈbɑːmɪnəbl/", meaning: "adj. 可恶的，极坏的", example: { en: "The weather was abominable.", cn: "天气糟透了。" } },
        { word: "aborigine", phonetic: "/ˌæbəˈrɪdʒəni/", meaning: "n. 土著居民", example: { en: "The aborigines have lived here for millennia.", cn: "土著居民在这里生活了数千年。" } },
        { word: "abortion", phonetic: "/əˈbɔːrʃn/", meaning: "n. 流产，中止", example: { en: "The project was an abortion from the start.", cn: "这个项目从一开始就注定要失败。" } },
        { word: "abraded", phonetic: "/əˈbreɪdɪd/", meaning: "adj. 磨损的", example: { en: "The abraded surface needed to be polished.", cn: "磨损的表面需要抛光。" } },
        { word: "abridgment", phonetic: "/əˈbrɪdʒmənt/", meaning: "n. 删节，缩短", example: { en: "The abridgment of the book made it more accessible.", cn: "这本书的删节版使其更易读。" } },
        { word: "abrogation", phonetic: "/ˌæbrəˈɡeɪʃn/", meaning: "n. 废除，取消", example: { en: "The abrogation of the treaty caused international tension.", cn: "条约的废除引起了国际紧张局势。" } },
        { word: "absconder", phonetic: "/əbˈskɑːndər/", meaning: "n. 潜逃者", example: { en: "The police are searching for the absconder.", cn: "警方正在搜寻潜逃者。" } },
        { word: "absolution", phonetic: "/ˌæbsəˈluːʃn/", meaning: "n. 赦免，免罪", example: { en: "He sought absolution for his sins.", cn: "他寻求赦免他的罪。" } },
        { word: "absorbed", phonetic: "/əbˈzɔːrbd/", meaning: "adj. 全神贯注的", example: { en: "She was completely absorbed in her book.", cn: "她全神贯注地看书。" } },
        { word: "absorber", phonetic: "/əbˈzɔːrbər/", meaning: "n. 吸收器，吸收剂", example: { en: "The shock absorber reduces vibration.", cn: "减震器减少振动。" } },
        { word: "abstainer", phonetic: "/əbˈsteɪnər/", meaning: "n. 戒酒者，弃权者", example: { en: "He's a total abstainer from alcohol.", cn: "他完全不喝酒。" } },
        { word: "abstractly", phonetic: "/ˈæbstræktli/", meaning: "adv. 抽象地", example: { en: "Think abstractly about the problem.", cn: "抽象地思考这个问题。" } },
        { word: "abstrusely", phonetic: "/əbˈstruːsli/", meaning: "adv. 深奥地", example: { en: "The concept was abstrusely explained.", cn: "这个概念解释得很深奥。" } },
        { word: "abutment", phonetic: "/əˈbʌtmənt/", meaning: "n. 桥台，邻接", example: { en: "The bridge abutment needs repair.", cn: "桥台需要维修。" } },
        { word: "abysmally", phonetic: "/əˈbɪzməli/", meaning: "adv. 极坏地", example: { en: "The team performed abysmally.", cn: "团队表现极差。" } },
        { word: "acceder", phonetic: "/əkˈsiːdər/", meaning: "n. 同意者，加入者", example: { en: "The new acceder to the treaty was welcomed.", cn: "新加入条约的成员国受到欢迎。" } },
        { word: "accentuation", phonetic: "/əkˌsentʃuˈeɪʃn/", meaning: "n. 强调，重读", example: { en: "The accentuation of certain words changed the meaning.", cn: "某些词的重读改变了意思。" } },
        { word: "acceptability", phonetic: "/əkˌseptəˈbɪləti/", meaning: "n. 可接受性", example: { en: "The acceptability of the proposal was questioned.", cn: "该提议的可接受性受到质疑。" } }
    ]
};

// 导出数据
if (typeof module !== 'undefined' && module.exports) {
    module.exports = wordDatabase;
}
